=== codeaudit/cougaar-qos/qos/src/org/cougaar/core/qos/frame/scale/testScale.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT testScale (contains | level3OnLevel2 | level2 | level6OnLevel5 | relationship | level1 | level5OnLevel4 | level5 | level1OnRoot | level2OnLevel1 | thing | level4 | level4OnLevel3 | root | level6 | level3)*>
<!ELEMENT contains EMPTY>
<!ATTLIST contains
          parent-value CDATA #IMPLIED
          child-value CDATA #IMPLIED>
<!ELEMENT level3OnLevel2 EMPTY>
<!ATTLIST level3OnLevel2
          parent-value CDATA #IMPLIED
          child-value CDATA #IMPLIED>
<!ELEMENT level2 EMPTY>
<!ATTLIST level2
          level2SlotString CDATA #IMPLIED
          level2SlotFloat CDATA #IMPLIED
          name CDATA #REQUIRED>
<!ELEMENT level6OnLevel5 EMPTY>
<!ATTLIST level6OnLevel5
          parent-value CDATA #IMPLIED
          child-value CDATA #IMPLIED>
<!ELEMENT relationship EMPTY>
<!ATTLIST relationship
          parent-value CDATA #IMPLIED
          child-value CDATA #IMPLIED>
<!ELEMENT level1 EMPTY>
<!ATTLIST level1
          level1SlotString CDATA #IMPLIED
          name CDATA #REQUIRED
          level1SlotFloat CDATA #IMPLIED>
<!ELEMENT level5OnLevel4 EMPTY>
<!ATTLIST level5OnLevel4
          parent-value CDATA #IMPLIED
          child-value CDATA #IMPLIED>
<!ELEMENT level5 EMPTY>
<!ATTLIST level5
          level5SlotFloat CDATA #IMPLIED
          level5SlotString CDATA #IMPLIED
          name CDATA #REQUIRED>
<!ELEMENT level1OnRoot EMPTY>
<!ATTLIST level1OnRoot
          parent-value CDATA #IMPLIED
          child-value CDATA #IMPLIED>
<!ELEMENT level2OnLevel1 EMPTY>
<!ATTLIST level2OnLevel1
          parent-value CDATA #IMPLIED
          child-value CDATA #IMPLIED>
<!ELEMENT thing EMPTY>
<!ATTLIST thing
          name CDATA #REQUIRED>
<!ELEMENT level4 EMPTY>
<!ATTLIST level4
          level4SlotFloat CDATA #IMPLIED
          level4SlotString CDATA #IMPLIED
          name CDATA #REQUIRED>
<!ELEMENT level4OnLevel3 EMPTY>
<!ATTLIST level4OnLevel3
          parent-value CDATA #IMPLIED
          child-value CDATA #IMPLIED>
<!ELEMENT root EMPTY>
<!ATTLIST root
          rootSlotFloat CDATA #IMPLIED
          avgLevel1 CDATA #IMPLIED
          name CDATA #REQUIRED
          count CDATA #IMPLIED
          rootSlotString CDATA #IMPLIED>
<!ELEMENT level6 EMPTY>
<!ATTLIST level6
          level6SlotFloat CDATA #IMPLIED
          name CDATA #REQUIRED
          level6SlotString CDATA #IMPLIED>
<!ELEMENT level3 EMPTY>
<!ATTLIST level3
          level3SlotString CDATA #IMPLIED
          name CDATA #REQUIRED
          level3SlotFloat CDATA #IMPLIED>

=== codeaudit/cougaar-qos/qos/src/org/cougaar/core/qos/frame/scale/initial-frames.xml
<!DOCTYPE testScale SYSTEM "testScale.dtd">
<!-- Copyright 2006 BBN Technologies Corp.  All Rights Reserved.  -->

<testScale>
	
	<root name="root" rootSlotFloat="10.0" rootSlotString="Root String"/>
	
	<level1 name="level 1" level1SlotFloat="11.0" level1SlotString="Level 1 String"/>
	
	<level1OnRoot parent-value="root" child-value="level 1"/>
	
	<level2 name="level 2" level2SlotFloat="12.0" level2SlotString="Level 2 String"/>
	
	<level2OnLevel1 parent-value="level 1" child-value="level 2"/>
	
	<level3  name="level 3" level3SlotFloat="13.0" level3SlotString="Level 3 String"/>
	
	<level3OnLevel2 parent-value="level 2" child-value="level 3"/>
	
	<level4 name="level 4" level4SlotFloat="14.0" level4SlotString="Level 4 String"/>
	
	<level4OnLevel3 parent-value="level 3" child-value="level 4"/>
	
	<level5 name="level 5" level5SlotFloat="15.0" level5SlotString="Level 5 String"/>
	
	<level5OnLevel4 parent-value="level 4" child-value="level 5"/>
	
	<level6 name="level 6" level6SlotFloat="16.0" level6SlotString="Level 6 String"/>
	
	<level6OnLevel5 parent-value="level 5" child-value="level 6"/>
	
</testScale>
